export type DeckStatus = "ready" | "processing" | "queued" | "failed";
export type DeckPreview = { id: string; title: string; course: string; lecture: string; source: string; basis: string; cards: number; updated: string; status: DeckStatus; statusDetail: string; learned?: number; processed?: number; totalPages?: number };
export type PreviewCard = { id: string; question: string; answer: string; source: string; section?: string; excerpt: string };

// Illustrative UI fixtures only; these do not describe a backend contract.
export const decks: DeckPreview[] = [
  { id: "vibe-coding", title: "Vibe Coding Setup", course: "Neue Konzepte", lecture: "Lecture 03", source: "Vibe Coding Setup.pdf", basis: "Zusammenfassung aus 18 Folien", cards: 24, updated: "2026-10-12", status: "ready", statusDetail: "Lernbereit · Beispiel", learned: 9 },
  { id: "network-security", title: "Network Security", course: "IT Security", lecture: "Lecture 08", source: "Network Security.pdf", basis: "Dokument mit 24 Seiten", cards: 24, updated: "2026-10-12", status: "processing", statusDetail: "Wird erstellt · 8 von 24 Seiten verarbeitet", processed: 8, totalPages: 24 },
  { id: "threat-modeling", title: "Threat Modeling", course: "Advanced Practical IT Security", lecture: "Lab 04", source: "Threat Modeling Lab.pdf", basis: "Zusammenfassung aus 12 Seiten", cards: 18, updated: "2026-10-12", status: "queued", statusDetail: "In Warteschlange · wartet auf Verarbeitung" },
  { id: "software-foundations", title: "Software Foundations", course: "Neue Konzepte", lecture: "Lecture 02", source: "Software Foundations.pdf", basis: "Dokument mit 16 Folien", cards: 20, updated: "2026-10-08", status: "failed", statusDetail: "Erstellung konnte nicht abgeschlossen werden" },
];

export const cards: PreviewCard[] = [
  { id: "meaning", question: "Was ist mit Vibe Coding gemeint?", answer: "Vibe Coding ist eine Arbeitsweise, bei der Software in kurzen Dialog- und Feedbackschleifen mit einem Coding-Assistenten entsteht. Ziele, Grenzen und Ergebnisse bleiben dabei für den Menschen überprüfbar.", source: "Vibe Coding Setup.pdf · Folien 3–4", section: "Zusammenfassung · Überblick", excerpt: "Natürliche Sprache steuert den Arbeitsprozess; fachliche Verantwortung und Prüfung bleiben beim Menschen." },
  { id: "context", question: "Warum ist Projektkontext wichtig?", answer: "Kontext macht Anforderungen prüfbar. Dazu gehören Projektstruktur, bestehende Konventionen, Einschränkungen und ein klar beschriebenes Ziel.", source: "Vibe Coding Setup.pdf · Folie 6", section: "Zusammenfassung · Zentrale Konzepte", excerpt: "Ohne passenden Kontext kann eine lokal plausible Änderung das Gesamtsystem verfehlen." },
  { id: "steps", question: "Weshalb sind kleine Änderungsschritte hilfreich?", answer: "Kleine Schritte begrenzen Risiken, vereinfachen Reviews und machen sichtbar, welche Änderung ein Ergebnis verursacht hat. Fehler lassen sich früher erkennen und gezielter korrigieren.", source: "Vibe Coding Setup.pdf · Folien 7–8", section: "Zusammenfassung · Feedbackschleife", excerpt: "Änderung, Prüfung und Korrektur bilden eine nachvollziehbare Feedbackschleife." },
  { id: "tests", question: "Welche Rolle spielen Tests?", answer: "Tests prüfen erwartbares Verhalten und schützen bestehende Funktionen. Sie liefern schnelles, reproduzierbares Feedback über eine Änderung.", source: "Vibe Coding Setup.pdf · Folie 12", section: "Zusammenfassung · Für die Prüfung", excerpt: "Generierter Code gilt erst nach geeigneter Validierung als belastbares Ergebnis." },
  { id: "responsibility", question: "Warum bleibt der Mensch für die Prüfung verantwortlich?", answer: "Ein Assistent kann überzeugend klingende, aber falsche oder unsichere Ergebnisse erzeugen. Der Mensch muss Code verstehen, Auswirkungen bewerten und die fachliche Freigabe verantworten.", source: "Vibe Coding Setup.pdf · Folie 12", section: "Zusammenfassung · Verantwortung behalten", excerpt: "Werkzeugausgaben ersetzen weder fachliches Verständnis noch Review und Sicherheitsprüfung." },
];
export const statusLabels: Record<DeckStatus, string> = { ready: "Bereit", processing: "Wird erstellt", queued: "In Warteschlange", failed: "Fehlgeschlagen" };
export function formatDate(value: string) { return new Date(`${value}T12:00:00Z`).toLocaleDateString("de-DE", { day: "2-digit", month: "2-digit", year: "numeric", timeZone: "UTC" }); }
